In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews=[
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go there',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot('nice food',50)

[4, 42]

In [13]:
vocab_size=50

encoded_reviews=[one_hot(d,vocab_size) for d in reviews]

In [15]:
encoded_reviews


[[4, 42],
 [5, 11],
 [19, 21],
 [47, 43, 30],
 [4, 48, 10],
 [38, 42],
 [29, 48, 10],
 [9, 27],
 [9, 8],
 [10, 28]]

In [20]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[ 4, 42,  0],
       [ 5, 11,  0],
       [19, 21,  0],
       [47, 43, 30],
       [ 4, 48, 10],
       [38, 42,  0],
       [29, 48, 10],
       [ 9, 27,  0],
       [ 9,  8,  0],
       [10, 28,  0]])

In [30]:
embedded_vector_size=4

model=Sequential()

model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

c:\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [31]:
X=padded_reviews
y=sentiment

In [32]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.fit(X,y,epochs=50,verbose=0)

In [37]:
loss,accuracy=model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6202


In [41]:
weights=model.get_layer('embedding').get_weights()[0]

In [42]:
len(weights)

50

In [43]:
weights[11]

array([-0.01257097, -0.08818468, -0.08845671,  0.03246999], dtype=float32)

In [44]:
weights[3]

array([ 0.04343779, -0.04123235,  0.04942175,  0.04964708], dtype=float32)